name: flutter_start
description: Flutter start project.
version: 1.0.1
author: QianyuIm
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

# 依赖
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 国际化
  flutter_localizations:
    sdk: flutter
  # 状态管理
  provider: ^5.0.0
  # 路径
  path_provider: ^2.0.1
  # 常用工具类库
  flustars: ^2.0.1
  # 屏幕适配工具
  flutter_screenutil: ^5.0.0+2
  # 获取当前设备信息
  device_info: ^2.0.1
  package_info: ^2.0.2
  #  firebase : only VPN
  # firebase_storage: ^8.1.0
  # 网络
  dio: ^4.0.0
  # ui
  pull_to_refresh: ^2.0.0
  # 带缓存的图片
  cached_network_image: ^3.0.0
  # 颜色
  colour: ^1.0.5
  # 星星组件
  flutter_rating_bar: ^4.0.0 
  # 底部抽屉
  sliding_up_panel: ^2.0.0+1
  
# 开发阶段依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  # json转换 eg: flutter packages pub run build_runner build
  json_serializable: ^4.1.2
  build_runner: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
  
   # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
  fonts:
    - family: KuaiLe # https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
    
    


flutter_intl:
  enabled: true
